server:
  port: 8085

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres-stocks:5432/postgres
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: liquidbase/changelog-master.yaml
    url: jdbc:postgresql://postgres-stocks:5432/postgres
    password: postgres
    user: postgres
    driver-class-name: org.postgresql.Driver

  main:
    banner-mode: off
