version: '3.1'

services:
  mongo:
    image: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - main-network

  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - "8081:8081"
    networks:
      - main-network
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

#  fbservice:
#    image: flatbuffer-document-service
#    restart: on-failure
#    depends_on:
#      - mongo
#    ports:
#      - "9002:9002"
#    environment:
#      - SERVER_PORT=9002
#      - SPRING_DATA_MONGODB_HOST=mongo
#      - SPRING_DATA_MONGODB_PORT=27017
#    networks:
#      - main-network
#
#  docservice:
#    image: document-service
#    restart: on-failure
#    depends_on:
#      - mongo
#    ports:
#      - "9001:9001"
#    environment:
#      - SERVER_PORT=9001
#      - SPRING_DATA_MONGODB_HOST=mongo
#      - SPRING_DATA_MONGODB_PORT=27017
#    networks:
#      - main-network

networks:
  main-network:
    external:
      name: CONTEST_NETWORK