version: '3.1'

networks:
  loadnetwork:
    driver: bridge

services:
  db:
    image: postgres
    container_name: postgres-stocks
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - loadnetwork

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - loadnetwork

# http://localhost:8085/api/v1/stocks
  stock-service-1:
    image: ere/stock-service
    container_name: stock-service-1
    ports:
      - "8085:8085"
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=stg
      - SERVER_PORT=8085
      - MANAGEMENT_PORT=8084
      - SERVICE_NAME=stock-service-1
      - HOSTNAME=docker_bridge
      - ROOT_LEVEL=info
    depends_on:
      - db
    networks:
      - loadnetwork

# http://localhost:8185/api/v1/stocks
  stock-service-2:
    image: ere/stock-service
    container_name: stock-service-2
    ports:
      - "8185:8185"
      - "8184:8184"
    environment:
      - SPRING_PROFILES_ACTIVE=stg
      - SERVER_PORT=8185
      - MANAGEMENT_PORT=8184
      - SERVICE_NAME=stock-service-2
      - HOSTNAME=docker_bridge
      - ROOT_LEVEL=info
    depends_on:
      - db
    networks:
      - loadnetwork

# http://localhost:8285/api/v1/stocks
  stock-service-3:
    image: ere/stock-service
    container_name: stock-service-3
    ports:
      - "8285:8285"
      - "8284:8284"
    environment:
      - SPRING_PROFILES_ACTIVE=stg
      - SERVER_PORT=8285
      - MANAGEMENT_PORT=8284
      - SERVICE_NAME=stock-service-3
      - HOSTNAME=docker_bridge
      - ROOT_LEVEL=info
    depends_on:
      - db
    networks:
      - loadnetwork

  grafana:
    image: grafana/grafana:latest
    container_name: lt_grafana
    ports:
      - "3000:3000"
    networks:
      - loadnetwork
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - loadnetwork

  nginx:
    image: nginx:latest
    container_name: lt-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - stock-service-1
      - stock-service-2
      - stock-service-3
    networks:
      - loadnetwork

volumes:
  grafana-storage:
  prometheus_data:
