global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: stock-service-1
    metrics_path: /actuator/prometheus # http://localhost:8084/actuator/prometheus
    static_configs:
      - targets: ['stock-service-1:8084']
  - job_name: stock-service-2
    metrics_path: /actuator/prometheus # http://localhost:8184/actuator/prometheus
    static_configs:
      - targets: ['stock-service-2:8184']
  - job_name: stock-service-3
    metrics_path: /actuator/prometheus # http://localhost:8284/actuator/prometheus
    static_configs:
      - targets: ['stock-service-3:8284']
