apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-stocks
spec:
  selector:
    matchLabels:
      app: postgres-stocks
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-stocks
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-stocks
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-stocks
